/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SoundpacksRouteImport } from './routes/soundpacks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LutsRouteImport } from './routes/luts'
import { Route as FashionRouteImport } from './routes/fashion'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SoundpacksRoute = SoundpacksRouteImport.update({
  id: '/soundpacks',
  path: '/soundpacks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LutsRoute = LutsRouteImport.update({
  id: '/luts',
  path: '/luts',
  getParentRoute: () => rootRouteImport,
} as any)
const FashionRoute = FashionRouteImport.update({
  id: '/fashion',
  path: '/fashion',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/connect': typeof ConnectRoute
  '/fashion': typeof FashionRoute
  '/luts': typeof LutsRoute
  '/settings': typeof SettingsRoute
  '/soundpacks': typeof SoundpacksRoute
  '/templates': typeof TemplatesRoute
  '/categories/$slug': typeof CategoriesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/connect': typeof ConnectRoute
  '/fashion': typeof FashionRoute
  '/luts': typeof LutsRoute
  '/settings': typeof SettingsRoute
  '/soundpacks': typeof SoundpacksRoute
  '/templates': typeof TemplatesRoute
  '/categories/$slug': typeof CategoriesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/connect': typeof ConnectRoute
  '/fashion': typeof FashionRoute
  '/luts': typeof LutsRoute
  '/settings': typeof SettingsRoute
  '/soundpacks': typeof SoundpacksRoute
  '/templates': typeof TemplatesRoute
  '/categories/$slug': typeof CategoriesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/connect'
    | '/fashion'
    | '/luts'
    | '/settings'
    | '/soundpacks'
    | '/templates'
    | '/categories/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/connect'
    | '/fashion'
    | '/luts'
    | '/settings'
    | '/soundpacks'
    | '/templates'
    | '/categories/$slug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/connect'
    | '/fashion'
    | '/luts'
    | '/settings'
    | '/soundpacks'
    | '/templates'
    | '/categories/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ConnectRoute: typeof ConnectRoute
  FashionRoute: typeof FashionRoute
  LutsRoute: typeof LutsRoute
  SettingsRoute: typeof SettingsRoute
  SoundpacksRoute: typeof SoundpacksRoute
  TemplatesRoute: typeof TemplatesRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soundpacks': {
      id: '/soundpacks'
      path: '/soundpacks'
      fullPath: '/soundpacks'
      preLoaderRoute: typeof SoundpacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luts': {
      id: '/luts'
      path: '/luts'
      fullPath: '/luts'
      preLoaderRoute: typeof LutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fashion': {
      id: '/fashion'
      path: '/fashion'
      fullPath: '/fashion'
      preLoaderRoute: typeof FashionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ConnectRoute: ConnectRoute,
  FashionRoute: FashionRoute,
  LutsRoute: LutsRoute,
  SettingsRoute: SettingsRoute,
  SoundpacksRoute: SoundpacksRoute,
  TemplatesRoute: TemplatesRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
