/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SoundpacksRouteImport } from './routes/soundpacks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LutsRouteImport } from './routes/luts'
import { Route as LightroomPresetsRouteImport } from './routes/lightroom-presets'
import { Route as FashionRouteImport } from './routes/fashion'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApparelRouteImport } from './routes/apparel'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates.index'
import { Route as LutsIndexRouteImport } from './routes/luts.index'
import { Route as LightroomPresetsIndexRouteImport } from './routes/lightroom-presets.index'
import { Route as ApparelIndexRouteImport } from './routes/apparel.index'
import { Route as TemplatesTemplateIdRouteImport } from './routes/templates.$templateId'
import { Route as LutsPresetIdRouteImport } from './routes/luts.$presetId'
import { Route as LightroomPresetsPresetIdRouteImport } from './routes/lightroom-presets.$presetId'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as ApparelProductIdRouteImport } from './routes/apparel.$productId'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SoundpacksRoute = SoundpacksRouteImport.update({
  id: '/soundpacks',
  path: '/soundpacks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LutsRoute = LutsRouteImport.update({
  id: '/luts',
  path: '/luts',
  getParentRoute: () => rootRouteImport,
} as any)
const LightroomPresetsRoute = LightroomPresetsRouteImport.update({
  id: '/lightroom-presets',
  path: '/lightroom-presets',
  getParentRoute: () => rootRouteImport,
} as any)
const FashionRoute = FashionRouteImport.update({
  id: '/fashion',
  path: '/fashion',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApparelRoute = ApparelRouteImport.update({
  id: '/apparel',
  path: '/apparel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TemplatesRoute,
} as any)
const LutsIndexRoute = LutsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LutsRoute,
} as any)
const LightroomPresetsIndexRoute = LightroomPresetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LightroomPresetsRoute,
} as any)
const ApparelIndexRoute = ApparelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApparelRoute,
} as any)
const TemplatesTemplateIdRoute = TemplatesTemplateIdRouteImport.update({
  id: '/$templateId',
  path: '/$templateId',
  getParentRoute: () => TemplatesRoute,
} as any)
const LutsPresetIdRoute = LutsPresetIdRouteImport.update({
  id: '/$presetId',
  path: '/$presetId',
  getParentRoute: () => LutsRoute,
} as any)
const LightroomPresetsPresetIdRoute =
  LightroomPresetsPresetIdRouteImport.update({
    id: '/$presetId',
    path: '/$presetId',
    getParentRoute: () => LightroomPresetsRoute,
  } as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApparelProductIdRoute = ApparelProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ApparelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apparel': typeof ApparelRouteWithChildren
  '/auth': typeof AuthRoute
  '/connect': typeof ConnectRoute
  '/fashion': typeof FashionRoute
  '/lightroom-presets': typeof LightroomPresetsRouteWithChildren
  '/luts': typeof LutsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/soundpacks': typeof SoundpacksRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/apparel/$productId': typeof ApparelProductIdRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/lightroom-presets/$presetId': typeof LightroomPresetsPresetIdRoute
  '/luts/$presetId': typeof LutsPresetIdRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/apparel/': typeof ApparelIndexRoute
  '/lightroom-presets/': typeof LightroomPresetsIndexRoute
  '/luts/': typeof LutsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/connect': typeof ConnectRoute
  '/fashion': typeof FashionRoute
  '/settings': typeof SettingsRoute
  '/soundpacks': typeof SoundpacksRoute
  '/apparel/$productId': typeof ApparelProductIdRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/lightroom-presets/$presetId': typeof LightroomPresetsPresetIdRoute
  '/luts/$presetId': typeof LutsPresetIdRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/apparel': typeof ApparelIndexRoute
  '/lightroom-presets': typeof LightroomPresetsIndexRoute
  '/luts': typeof LutsIndexRoute
  '/templates': typeof TemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apparel': typeof ApparelRouteWithChildren
  '/auth': typeof AuthRoute
  '/connect': typeof ConnectRoute
  '/fashion': typeof FashionRoute
  '/lightroom-presets': typeof LightroomPresetsRouteWithChildren
  '/luts': typeof LutsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/soundpacks': typeof SoundpacksRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/apparel/$productId': typeof ApparelProductIdRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/lightroom-presets/$presetId': typeof LightroomPresetsPresetIdRoute
  '/luts/$presetId': typeof LutsPresetIdRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/apparel/': typeof ApparelIndexRoute
  '/lightroom-presets/': typeof LightroomPresetsIndexRoute
  '/luts/': typeof LutsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apparel'
    | '/auth'
    | '/connect'
    | '/fashion'
    | '/lightroom-presets'
    | '/luts'
    | '/settings'
    | '/soundpacks'
    | '/templates'
    | '/apparel/$productId'
    | '/categories/$slug'
    | '/lightroom-presets/$presetId'
    | '/luts/$presetId'
    | '/templates/$templateId'
    | '/apparel/'
    | '/lightroom-presets/'
    | '/luts/'
    | '/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/connect'
    | '/fashion'
    | '/settings'
    | '/soundpacks'
    | '/apparel/$productId'
    | '/categories/$slug'
    | '/lightroom-presets/$presetId'
    | '/luts/$presetId'
    | '/templates/$templateId'
    | '/apparel'
    | '/lightroom-presets'
    | '/luts'
    | '/templates'
  id:
    | '__root__'
    | '/'
    | '/apparel'
    | '/auth'
    | '/connect'
    | '/fashion'
    | '/lightroom-presets'
    | '/luts'
    | '/settings'
    | '/soundpacks'
    | '/templates'
    | '/apparel/$productId'
    | '/categories/$slug'
    | '/lightroom-presets/$presetId'
    | '/luts/$presetId'
    | '/templates/$templateId'
    | '/apparel/'
    | '/lightroom-presets/'
    | '/luts/'
    | '/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApparelRoute: typeof ApparelRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConnectRoute: typeof ConnectRoute
  FashionRoute: typeof FashionRoute
  LightroomPresetsRoute: typeof LightroomPresetsRouteWithChildren
  LutsRoute: typeof LutsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SoundpacksRoute: typeof SoundpacksRoute
  TemplatesRoute: typeof TemplatesRouteWithChildren
  CategoriesSlugRoute: typeof CategoriesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soundpacks': {
      id: '/soundpacks'
      path: '/soundpacks'
      fullPath: '/soundpacks'
      preLoaderRoute: typeof SoundpacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luts': {
      id: '/luts'
      path: '/luts'
      fullPath: '/luts'
      preLoaderRoute: typeof LutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lightroom-presets': {
      id: '/lightroom-presets'
      path: '/lightroom-presets'
      fullPath: '/lightroom-presets'
      preLoaderRoute: typeof LightroomPresetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fashion': {
      id: '/fashion'
      path: '/fashion'
      fullPath: '/fashion'
      preLoaderRoute: typeof FashionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apparel': {
      id: '/apparel'
      path: '/apparel'
      fullPath: '/apparel'
      preLoaderRoute: typeof ApparelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/luts/': {
      id: '/luts/'
      path: '/'
      fullPath: '/luts/'
      preLoaderRoute: typeof LutsIndexRouteImport
      parentRoute: typeof LutsRoute
    }
    '/lightroom-presets/': {
      id: '/lightroom-presets/'
      path: '/'
      fullPath: '/lightroom-presets/'
      preLoaderRoute: typeof LightroomPresetsIndexRouteImport
      parentRoute: typeof LightroomPresetsRoute
    }
    '/apparel/': {
      id: '/apparel/'
      path: '/'
      fullPath: '/apparel/'
      preLoaderRoute: typeof ApparelIndexRouteImport
      parentRoute: typeof ApparelRoute
    }
    '/templates/$templateId': {
      id: '/templates/$templateId'
      path: '/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof TemplatesTemplateIdRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/luts/$presetId': {
      id: '/luts/$presetId'
      path: '/$presetId'
      fullPath: '/luts/$presetId'
      preLoaderRoute: typeof LutsPresetIdRouteImport
      parentRoute: typeof LutsRoute
    }
    '/lightroom-presets/$presetId': {
      id: '/lightroom-presets/$presetId'
      path: '/$presetId'
      fullPath: '/lightroom-presets/$presetId'
      preLoaderRoute: typeof LightroomPresetsPresetIdRouteImport
      parentRoute: typeof LightroomPresetsRoute
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apparel/$productId': {
      id: '/apparel/$productId'
      path: '/$productId'
      fullPath: '/apparel/$productId'
      preLoaderRoute: typeof ApparelProductIdRouteImport
      parentRoute: typeof ApparelRoute
    }
  }
}

interface ApparelRouteChildren {
  ApparelProductIdRoute: typeof ApparelProductIdRoute
  ApparelIndexRoute: typeof ApparelIndexRoute
}

const ApparelRouteChildren: ApparelRouteChildren = {
  ApparelProductIdRoute: ApparelProductIdRoute,
  ApparelIndexRoute: ApparelIndexRoute,
}

const ApparelRouteWithChildren =
  ApparelRoute._addFileChildren(ApparelRouteChildren)

interface LightroomPresetsRouteChildren {
  LightroomPresetsPresetIdRoute: typeof LightroomPresetsPresetIdRoute
  LightroomPresetsIndexRoute: typeof LightroomPresetsIndexRoute
}

const LightroomPresetsRouteChildren: LightroomPresetsRouteChildren = {
  LightroomPresetsPresetIdRoute: LightroomPresetsPresetIdRoute,
  LightroomPresetsIndexRoute: LightroomPresetsIndexRoute,
}

const LightroomPresetsRouteWithChildren =
  LightroomPresetsRoute._addFileChildren(LightroomPresetsRouteChildren)

interface LutsRouteChildren {
  LutsPresetIdRoute: typeof LutsPresetIdRoute
  LutsIndexRoute: typeof LutsIndexRoute
}

const LutsRouteChildren: LutsRouteChildren = {
  LutsPresetIdRoute: LutsPresetIdRoute,
  LutsIndexRoute: LutsIndexRoute,
}

const LutsRouteWithChildren = LutsRoute._addFileChildren(LutsRouteChildren)

interface TemplatesRouteChildren {
  TemplatesTemplateIdRoute: typeof TemplatesTemplateIdRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesTemplateIdRoute: TemplatesTemplateIdRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApparelRoute: ApparelRouteWithChildren,
  AuthRoute: AuthRoute,
  ConnectRoute: ConnectRoute,
  FashionRoute: FashionRoute,
  LightroomPresetsRoute: LightroomPresetsRouteWithChildren,
  LutsRoute: LutsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SoundpacksRoute: SoundpacksRoute,
  TemplatesRoute: TemplatesRouteWithChildren,
  CategoriesSlugRoute: CategoriesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
